// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebControlLibrary.Models.Entites;

#nullable disable

namespace WebControlLibrary.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C2279156CD0F");

                    b.HasIndex(new[] { "Isbn" }, "UQ__Books__447D36EA9250F971")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Borrowing", b =>
                {
                    b.Property<int>("BorrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BorrowID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BorrowId"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<DateOnly>("BorrowDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int")
                        .HasColumnName("ReaderID");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("BorrowId")
                        .HasName("PK__Borrowin__4295F85F7F37564F");

                    b.HasIndex("BookId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Borrowing", (string)null);
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Reader", b =>
                {
                    b.Property<int>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReaderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReaderId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReaderId")
                        .HasName("PK__Readers__8E67A581499F9ACA");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Returning", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int?>("BorrowId")
                        .HasColumnType("int")
                        .HasColumnName("BorrowID");

                    b.Property<decimal?>("LateFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("ReturnId")
                        .HasName("PK__Returnin__F445E988277AFD62");

                    b.HasIndex("BorrowId");

                    b.ToTable("Returning", (string)null);
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Borrowing", b =>
                {
                    b.HasOne("WebControlLibrary.Models.Entites.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK__Borrowing__BookI__5070F446");

                    b.HasOne("WebControlLibrary.Models.Entites.Reader", "Reader")
                        .WithMany("Borrowings")
                        .HasForeignKey("ReaderId")
                        .HasConstraintName("FK__Borrowing__Reade__4F7CD00D");

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Returning", b =>
                {
                    b.HasOne("WebControlLibrary.Models.Entites.Borrowing", "Borrow")
                        .WithMany("Returnings")
                        .HasForeignKey("BorrowId")
                        .HasConstraintName("FK__Returning__Borro__5441852A");

                    b.Navigation("Borrow");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Book", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Borrowing", b =>
                {
                    b.Navigation("Returnings");
                });

            modelBuilder.Entity("WebControlLibrary.Models.Entites.Reader", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
